"""Core RLM loop and protocol definitions."""

from .capabilities import (
    JSON_SCHEMA_2020_12,
    CapabilityAdmission,
    CapabilityAnnotator,
    CapabilityAttemptAuthority,
    CapabilityBroker,
    CapabilityCall,
    CapabilityCallError,
    CapabilityCancelled,
    CapabilityCheckpoint,
    CapabilityDeadlineExceeded,
    CapabilityDescriptor,
    CapabilityError,
    CapabilityErrorCode,
    CapabilityExecutionContext,
    CapabilityGuard,
    CapabilityId,
    CapabilityKind,
    CapabilityManifest,
    CapabilityMetadata,
    CapabilityMetric,
    CapabilityObserver,
    CapabilityOutcome,
    CapabilityRegistration,
    CapabilityReservation,
    CapabilityResult,
    CapabilityResultHandle,
    CapabilityStatus,
    EvidenceLocation,
    EvidenceRange,
    PaginationMode,
    ProviderOperation,
    ResultDelivery,
    SchemaSpec,
    SideEffect,
    generate_binding,
    validate_call,
)
from .clients.anthropic import AnthropicClient, AnthropicSubcallClient
from .clients.modelrelay import ModelRelayClient, ModelRelaySubcallClient
from .clients.openai_compat import OpenAICompatClient, OpenAICompatSubcallClient
from .environments import EnvironmentConfig, create_environment, create_environment_context
from .exceptions import (
    BatchItemError,
    BatchItemErrorDetails,
    PolicyError,
    RLMError,
)
from .execution.budget import (
    DEFAULT_DEPTH_BUDGET,
    DEFAULT_ROOT_OUTPUT_TOKENS,
    DEFAULT_SUBCALL_BUDGET,
    DEFAULT_SUBCALL_OUTPUT_TOKENS,
    DEFAULT_TOKEN_BUDGET,
    DEFAULT_WALL_TIME_MS,
    Budget,
    BudgetExhausted,
    BudgetLedger,
    BudgetRequest,
    BudgetReservation,
    BudgetSnapshot,
)
from .execution.config import DEFAULT_OUTPUT_CHARS, ExecutionConfig, SandboxLimits
from .execution.context import ExecutionContext, create_execution_context
from .execution.progress import ProgressCallback, emit_progress
from .execution.stats import ExecutionStats
from .execution.trace import (
    TRACE_ABI_VERSION,
    DataUseAuthorization,
    PersistenceClass,
    RunEvent,
    RunRecord,
    TraceRetentionPolicy,
    parse_event,
)
from .loop.code_extractor import extract_code_block
from .loop.rlm import RLMConfig, RLMResult, run_rlm
from .policy import PolicyHints
from .prompts.builder import SystemPromptBuilder
from .prompts.pack import (
    PromptPack,
    PromptPackBinding,
    PromptPackCatalog,
    PromptPackError,
    PromptPackRecord,
    load_prompt_pack,
    resolve_prompt_pack,
)
from .protocols.environment import EnvCapabilities, ExecutionResult, RLMEnvironment
from .protocols.llm_client import LLMClient, TokenUsage
from .protocols.subcall_client import SubcallClient, SubcallOutputTokenLimitProvider
from .providers import (
    PROVIDER_PROTOCOL_VERSION,
    BoundSource,
    ConfiguredSource,
    ProviderCatalog,
    ProviderManifest,
    ProviderRegistration,
    ProviderRegistry,
    ProviderRuntime,
)
from .structured import aggregate_json_counts, structured_batch, validate_json

__all__ = [
    "run_rlm",
    "RLMConfig",
    "RLMResult",
    "extract_code_block",
    "DEFAULT_TOKEN_BUDGET",
    "DEFAULT_SUBCALL_BUDGET",
    "DEFAULT_DEPTH_BUDGET",
    "DEFAULT_WALL_TIME_MS",
    "DEFAULT_ROOT_OUTPUT_TOKENS",
    "DEFAULT_SUBCALL_OUTPUT_TOKENS",
    "DEFAULT_OUTPUT_CHARS",
    "Budget",
    "BudgetExhausted",
    "BudgetLedger",
    "BudgetRequest",
    "BudgetReservation",
    "BudgetSnapshot",
    "SandboxLimits",
    "ExecutionConfig",
    "ExecutionStats",
    "EnvironmentConfig",
    "create_environment",
    "create_environment_context",
    "ExecutionContext",
    "create_execution_context",
    "ProgressCallback",
    "emit_progress",
    "RLMError",
    "BatchItemError",
    "BatchItemErrorDetails",
    "PolicyError",
    "PolicyHints",
    "RLMEnvironment",
    "EnvCapabilities",
    "ExecutionResult",
    "LLMClient",
    "TokenUsage",
    "SubcallClient",
    "SubcallOutputTokenLimitProvider",
    "SystemPromptBuilder",
    "PromptPack",
    "PromptPackBinding",
    "PromptPackCatalog",
    "PromptPackError",
    "PromptPackRecord",
    "load_prompt_pack",
    "resolve_prompt_pack",
    "AnthropicClient",
    "AnthropicSubcallClient",
    "ModelRelayClient",
    "ModelRelaySubcallClient",
    "OpenAICompatClient",
    "OpenAICompatSubcallClient",
    "structured_batch",
    "validate_json",
    "aggregate_json_counts",
    "CapabilityBroker",
    "CapabilityAdmission",
    "CapabilityAttemptAuthority",
    "CapabilityCall",
    "CapabilityCallError",
    "CapabilityCancelled",
    "CapabilityCheckpoint",
    "CapabilityDeadlineExceeded",
    "CapabilityDescriptor",
    "CapabilityError",
    "CapabilityErrorCode",
    "CapabilityExecutionContext",
    "CapabilityGuard",
    "CapabilityId",
    "CapabilityKind",
    "CapabilityManifest",
    "CapabilityMetadata",
    "CapabilityMetric",
    "CapabilityObserver",
    "CapabilityOutcome",
    "CapabilityRegistration",
    "CapabilityReservation",
    "CapabilityResult",
    "CapabilityResultHandle",
    "CapabilityStatus",
    "CapabilityAnnotator",
    "EvidenceLocation",
    "EvidenceRange",
    "JSON_SCHEMA_2020_12",
    "PaginationMode",
    "ProviderOperation",
    "ResultDelivery",
    "SchemaSpec",
    "SideEffect",
    "generate_binding",
    "validate_call",
    "TRACE_ABI_VERSION",
    "DataUseAuthorization",
    "PersistenceClass",
    "RunEvent",
    "RunRecord",
    "TraceRetentionPolicy",
    "parse_event",
    "PROVIDER_PROTOCOL_VERSION",
    "BoundSource",
    "ConfiguredSource",
    "ProviderCatalog",
    "ProviderManifest",
    "ProviderRegistration",
    "ProviderRegistry",
    "ProviderRuntime",
]
